[package]
name = "vmm"
version = "0.1.0"
edition = "2018"

[dependencies]
epoll = "4.3.1"
kvm-bindings = { version = "0.5.0", features = ["fam-wrappers"] }
kvm-ioctls = "0.11.0"
libc = "0.2.91"
# TODO: Maybe move devices module into a crate
# Used by devices
thiserror = "1.0.30"
linux-loader = { version = "0.4.0", features = ["bzimage", "elf"] }
vm-memory = { version = "0.7.0", features = ["backend-mmap"] }
vmm-sys-util = "0.9.0"
event-manager = { version = "0.2.1", features = ["remote_endpoint"] }

# vm-device is not yet published on crates.io.
# To make sure that breaking changes to vm-device are not breaking the
# vm-vcpu build, we're using a fixed revision.
vm-device = { git = "https://github.com/rust-vmm/vm-device", rev = "5847f12" }

# These 3 crates are related to VirtIO implementation
virtio-blk = { git = "https://github.com/rust-vmm/vm-virtio.git", features = ["backend-stdio"] }
virtio-device = { git = "https://github.com/rust-vmm/vm-virtio.git"}
virtio-queue = { git = "https://github.com/rust-vmm/vm-virtio.git"}

vm-superio = "0.4.0"
